site_name: Gretchen - Documentation
nav:
  - The Gretchen robot:
    - '1_index.md'
  - Gretchen - Hardware:
    - '2_hardware_intro.md'
    - '3_wooden_parts.md'
    - '4_drive_parts.md'
    - '5_printed_3d.md'
    - '6_servo_el_comp.md'
    - '7_cables_wires.md'
    - '8_power_supply.md'
  - Gretchen - Software:
    - '9_software_intro.md'
    - '10_firmware.md'
    - '11_motor_control.md'
    - '12_libsensorimotor.md'
  - SImulation:
    - '13_webots.md'
  - Projects and Conferences:
    - '14_current_progress.md'
    - '15_conferences.md'
    - '16_projects.md'
    - '17_links.md'

theme:
  name: material
  favicon: img/favicon.ico
  logo: img_gretchen/gretchen_standing_wb.jpg
  custom_dir: overrides
  features:
    - navigation.sections

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/naoteamhumboldt
    - icon: fontawesome/brands/github
      link: https://github.com/BerlinUnited
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/teamhumboldt